### ISSUE TITLE
Bot won't reply in Telegram

### ISSUE THREAD

**Issue by ekimbasoglu** [flows-network/openai-assistant-telegram#2]
Hello👋

I have an active telegram bot and I restarted it by pausing and unpausing but the bot won't respond.

I checked the configuration for each key and there is no problem, I have credit on my OpenAI account as well.
The link to the bot is; https://flows.network/flow/info/JobMasterOvde-Bot

![image](https://github.com/user-attachments/assets/f64b4688-86f9-4309-b488-b34ffebe6460)
It responds when I type `/restart` but still doesn't send me any messages on telegram.
![image](https://github.com/user-attachments/assets/09ab9c23-953a-4179-8b2c-218588b7ffd7)

Something in `run_message` got broken when they updated the API, could somebody show how to debug this project?

**Comment by ekimbasoglu** [comment]
Update: I found out why it's not responding. Currently, Assistants v1 is updated with v2 and the newer models then 3.5-turbo is not supported with v1 anymore. The current code still uses v1. I don't have the necessary code to update the project, could someone please reach out via email(ekimbasoglu) or in GitHub? 👀  @DarumaDocker @alabulei1 

`{ "level": "ERROR", "msg": "thread '' panicked at src/lib.rs:106:10:\ncalled `Result::unwrap()` on an `Err` value: ApiError(ApiError { message: \"The requested model 'gpt-4o-mini-2024-07-18' cannot be used with the Assistants API in v1. Follow the migration guide to upgrade to v2: https://platform.openai.com/docs/assistants/migration.\", type: Some(\"invalid_request_error\"), param: Some(String(\"model\")), code: Some(String(\"unsupported_model\")) })\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n", "function": "run" }
`

**Comment by juntao** [comment]
The `ASSISTANT_ID` environment var associated with your bot is configured with the model it needs to be. You need to log into your openai account and change the model setting for that `ASSISTANT_ID`

**Comment by ekimbasoglu** [comment]
@juntao Thank you for your reply and help, instead of this solution/project, I continued using the LLama/HuggingFace model because it's free. I'm closing this issue now 💯
